name: r_resources
description: Builder package for generating R-resources file
version: 0.0.4
author: solitaryhat@yandex.ru
homepage: https://github.com/SolitaryHat/r_resources

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  build: ^1.6.3
  path: ^1.8.0
  glob: ^2.0.0
  yaml: ^3.1.0
  meta: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_test: ^1.3.7
  effective_dart: ^1.3.0