name: r_resources
description: Builder package for generating R-resources file
version: 0.0.1
author: solitaryhat@yandex.ru
homepage: https://github.com/SolitaryHat/r_resources

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  build: ^1.6.0
  path: ^1.7.0
  glob: ^1.2.0
  yaml: ^2.2.1
  meta: ^1.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_test: ^1.3.2
  effective_dart: ^1.3.0