name: r_resources
description: Builder package for generating R file which contains project asset references
version: 0.0.6
homepage: https://github.com/SolitaryHat/r_resources

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  build: ^2.0.0
  path: ^1.8.0
  glob: ^2.0.0
  yaml: ^3.1.0
  meta: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_test: ^2.0.0
  effective_dart: ^1.3.1