/// THIS FILE IS GENERATED BY flutter_resources. DO NOT MODIFY MANULLY.

// ignore_for_file: always_specify_types,lines_longer_than_80_chars,non_constant_identifier_names,prefer_double_quotes
class R {
}


