name: PR checks

on:
  pull_request:
    branches: 
      - "main"
    paths-ignore:
      - "CHANGELOG.md"
      - "LICENSE"
      - ".gitignore"
      - "README.md"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: ( cd example ; flutter pub run build_runner build )
      - run: flutter analyze
      - run: flutter test
